<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="healthCheck.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
